// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5Y7-QmJ2qp_BcqMds5ZdOoow1xJV3iM',
    appId: '1:1067547731215:web:c24c7c29d9c9e853e48a7a',
    messagingSenderId: '1067547731215',
    projectId: 'smart-tax-zra',
    authDomain: 'smart-tax-zra.firebaseapp.com',
    storageBucket: 'smart-tax-zra.firebasestorage.app',
    measurementId: 'G-BTN8G7W8XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeRiM6wqCSJkx9Q_oWE9OhmWpXG52lZWM',
    appId: '1:1067547731215:android:dd10f71182f09096e48a7a',
    messagingSenderId: '1067547731215',
    projectId: 'smart-tax-zra',
    storageBucket: 'smart-tax-zra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VdtSZOFtAMxOB_7-VTZ_szMEB6M8H9U',
    appId: '1:1067547731215:ios:7de4e436208904fbe48a7a',
    messagingSenderId: '1067547731215',
    projectId: 'smart-tax-zra',
    storageBucket: 'smart-tax-zra.firebasestorage.app',
    androidClientId: '1067547731215-om0op3bo0ifov4d3rplcgpq2qlovns9t.apps.googleusercontent.com',
    iosClientId: '1067547731215-b6e121nd7m3kt90kka51ckbprq18n5tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPayZra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VdtSZOFtAMxOB_7-VTZ_szMEB6M8H9U',
    appId: '1:1067547731215:ios:7de4e436208904fbe48a7a',
    messagingSenderId: '1067547731215',
    projectId: 'smart-tax-zra',
    storageBucket: 'smart-tax-zra.firebasestorage.app',
    androidClientId: '1067547731215-om0op3bo0ifov4d3rplcgpq2qlovns9t.apps.googleusercontent.com',
    iosClientId: '1067547731215-b6e121nd7m3kt90kka51ckbprq18n5tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPayZra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5Y7-QmJ2qp_BcqMds5ZdOoow1xJV3iM',
    appId: '1:1067547731215:web:cfc20bad9fc7d54ce48a7a',
    messagingSenderId: '1067547731215',
    projectId: 'smart-tax-zra',
    authDomain: 'smart-tax-zra.firebaseapp.com',
    storageBucket: 'smart-tax-zra.firebasestorage.app',
    measurementId: 'G-3TK7XRL00M',
  );
}
